---
# Cluster storage options.
storage_type: filesystem  # options: 'filesystem', 'zfs'
storage_zfs_pool_name: zfsdata
# storage_nfs_dir: '{{ storage_zfs_pool_name }}'  # Use this for 'zfs'
storage_nfs_dir: "mnt/k3s" # Use this for 'filesystem'
storage_nfs_share_name: k3s-pvc # /mnt/k3s/k3s-pvc
storage_nfs_mount_drive: /dev/sda1
storage_nfs_mount_fstype: vfat #ext4
storage_nfs_mount_drive_enable: true

storage_k3s_server_dir: "k3s-data" # /mnt/k3s/k3s-data
storage_k3s_server_bind_enabled: false

# Drupal installation options.
drupal_image: drupal:10.2-apache
drupal_hash_salt: OTk4MTYzYWI4N2E2MGIxNjlmYmQ2MTA4
drupal_trusted_host_patterns: '^.+$'
drupal_database_password: 'drupal'
drupal_base_web_path: '/var/www/html/sites/default/'
drupal_config_sync_directory: 'sites/default/files/config_OTk4MTYzY'
drupal_extra_settings_php: ''

# These networking variables are only necessary if using optional static and
# remote networking features in the `tasks/networking` playbooks.
ipv4_subnet_prefix: "10.1.1"
ipv4_gateway: "10.1.1.1"
dns4_servers: "{{ ipv4_gateway }}"
active_internet_interface: "wlan0"
reverse_tunnel_enable: false
reverse_tunnel_vps_username: my-vps-username
reverse_tunnel_vps_hostname: my-vps-hostname
control_plane_router_setup: false
