---
- name: Ensure NFS share directory exists.
  ansible.builtin.file:
    dest: "/{{ storage_nfs_dir }}/{{ storage_nfs_share_name }}"
    state: directory
    mode: 0777

- name: Ensure storage k3s server dirr exists
  ansible.builtin.file:
    path: /{{ storage_nfs_dir }}/{{ storage_k3s_server_dir }}
    state: directory
    mode: 0755
  when: storage_k3s_server_bind_enabled

- name: Ensure the NFS volume is mounted from "external storage".
  ansible.posix.mount:
    src: "{{ storage_nfs_mount_drive }}"
    path: "/{{ storage_nfs_dir }}"
    opts: defaults,nofail,noatime
    fstype: "{{ storage_nfs_mount_fstype }}"
    state: mounted
  when: storage_nfs_mount_drive_enable

- name: Ensure NFS is installed.
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Bind mount K3s server directory
  ansible.posix.mount:
    src: /{{ storage_nfs_dir }}/{{ storage_k3s_server_dir }}
    path: /var/lib/rancher/k3s/server
    fstype: none
    opts: bind,nofail
    state: mounted
  when: storage_k3s_server_bind_enabled

- name: Configure NFS exports.
  ansible.builtin.lineinfile:
    dest: /etc/exports
    line: "/{{ storage_nfs_dir }}/{{ storage_nfs_share_name }}    *(rw,sync,no_root_squash)"
    regexp: ".*"
    create: true
  notify: restart nfs

- name: Ensure NFS is started and enabled at boot.
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true
